#!/usr/bin/env python3
"""
generate-cursor-packs.py — Windowsカーソル配布用 zip生成
- 各タレント 15種 (appstar,arrow,beam,cross,hand,help,move,no,pen,person,sizenesw,sizens,sizenwse,sizewe,wait) を
  install.inf + README.md + LICENSE + preview.png と共に zip化
- Scheme名: MilliOrbis-{CapEnglish} (例: MilliOrbis-Mahoro, MilliOrbis-MilliChan)
- 出力: dist/cursors/MilliOrbis-*.zip (Git管理外) + 各フォルダに install.inf/README.md/preview.png を配置（検証用）
"""
import os, pathlib, zipfile, textwrap, shutil, re, json, struct, argparse, plistlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CURSORS_ROOT = ROOT / "images" / "cursors"
DIST_ROOT = ROOT / "dist" / "cursors"

# Portal id -> display + scheme mapping
TALENTS = [
    ("konomi", "Konomi", "甘狼このみ"),
    ("nono", "Nono", "音ノ乃のの"),
    ("akubi", "Akubi", "あくび・でもんすぺーど"),
    ("koma", "Koma", "小廻こま"),
    ("rako", "Rako", "音ノ瀬らこ"),  # cur folder is rako
    ("yura", "Yura", "ゆらぎゆら"),
    ("nuhu", "Nuhu", "虹深°ぬふ"),
    ("tsukuri", "Tsukuri", "眠雲ツクリ"),
    ("rizu", "Rizu", "雨夜リズ"),  # portal liz -> cur rizu
    ("rei", "Rei", "夕霧レイ"),
    ("mahoro", "Mahoro", "鹿乃まほろ"),
    ("milli-chan", "MilliChan", "ミリちゃん"),
]

# Mapping for portal id vs cur folder id
CUR_FOLDER = {
    "konomi": "konomi",
    "nono": "nono",
    "akubi": "akubi",
    "koma": "koma",
    "rako": "rako",
    "yura": "yura",
    "nuhu": "nuhu",
    "tsukuri": "tsukuri",
    "rizu": "rizu",
    "rei": "rei",
    "mahoro": "mahoro",
    "milli-chan": "milli-chan",
}
# For website portal id liz -> rizu
PORTAL_ID = {
    "konomi": "konomi",
    "nono": "nono",
    "akubi": "akubi",
    "koma": "koma",
    "rako": "raco",
    "yura": "yura",
    "nuhu": "nuhu",
    "tsukuri": "tsukuri",
    "rizu": "liz",
    "rei": "rei",
    "mahoro": "mahoro",
    "milli-chan": "milchan",
}

FIFTEEN = ["appstar.cur","arrow.cur","beam.cur","cross.cur","hand.cur","help.cur","move.cur","no.cur","pen.cur","person.cur","sizenesw.cur","sizens.cur","sizenwse.cur","sizewe.cur","wait.cur"]

INF_TEMPLATE = r"""; MilliOrbis {JP} Cursor Scheme — Right-click > Install (Admin required)
; Generated by scripts/generate-cursor-packs.py
; Scheme: {SCHEME}
; Based on david-ly gist MIT template, adapted for MilliOrbis
[Version]
Signature="$Windows NT$"

[DefaultInstall]
CopyFiles=Cursors.Files
AddReg=Cursors.Reg

[DestinationDirs]
Cursors.Files=10,"%CUR_DIR%"

[Cursors.Files]
appstar.cur
arrow.cur
beam.cur
cross.cur
hand.cur
help.cur
move.cur
no.cur
pen.cur
person.cur
sizenesw.cur
sizens.cur
sizenwse.cur
sizewe.cur
wait.cur

[Cursors.Reg]
HKCU,"Control Panel\Cursors\Schemes","%SCHEME_NAME%","%10%\%CUR_DIR%\%pointer%,%10%\%CUR_DIR%\%help%,%10%\%CUR_DIR%\%work%,%10%\%CUR_DIR%\%busy%,%10%\%CUR_DIR%\%cross%,%10%\%CUR_DIR%\%text%,%10%\%CUR_DIR%\%hand%,%10%\%CUR_DIR%\%unavailable%,%10%\%CUR_DIR%\%vert%,%10%\%CUR_DIR%\%horz%,%10%\%CUR_DIR%\%dgn1%,%10%\%CUR_DIR%\%dgn2%,%10%\%CUR_DIR%\%move%,%10%\%CUR_DIR%\%alternate%,%10%\%CUR_DIR%\%link%,%10%\%CUR_DIR%\%pin%,%10%\%CUR_DIR%\%person%"

[Strings]
CUR_DIR     = "Cursors\{SCHEME}"
SCHEME_NAME = "{SCHEME}"
pointer     = "arrow.cur"
help        = "help.cur"
work        = "appstar.cur"
busy        = "wait.cur"
cross       = "cross.cur"
text        = "beam.cur"
hand        = "pen.cur"
unavailable = "no.cur"
vert        = "sizens.cur"
horz        = "sizewe.cur"
dgn1        = "sizenwse.cur"
dgn2        = "sizenesw.cur"
move        = "move.cur"
alternate   = "arrow.cur"
link        = "hand.cur"
pin         = "hand.cur"
person      = "person.cur"
"""

README_TEMPLATE = """# MilliOrbis {JP} Cursors for Windows

![preview](preview.png)

**{JP}（{EN}）** のオリジナルカーソル 15種（`arrow` / `appstar` / `beam` / `cross` / `hand` / `help` / `move` / `no` / `pen` / `person` / `sizenesw` / `sizens` / `sizenwse` / `sizewe` / `wait`）を Windows のマウスポインターとして使えます。ホットスポット（矢印の先端等）は調整済みです。

## インストール（Windows 10 / 11）— INFで一括登録

1. `MilliOrbis-{EN}.zip` を解凍 → フォルダ `MilliOrbis-{EN}/` を開く
2. `install.inf` を **右クリック → インストール**（Windows 11 は `その他のオプションを表示 → インストール`）→ UACで `はい`
3. `設定 → Bluetoothとデバイス → マウス → その他のマウス設定 → ポインター` を開く
4. `配色`（Scheme）で `MilliOrbis-{EN}` を選択 → `適用` → `OK`

> 右クリックに `インストール` が出ない場合: 解凍できているか確認してください。ZIPのままでは表示されません。代替として `install.bat` を右クリック → 管理者として実行 でも登録できます。

### 手動で割り当てる場合（INFが使えない環境）

`設定 → Bluetoothとデバイス → マウス → その他のマウス設定 → ポインター` で各役割を `参照` から個別に指定 → `名前を付けて保存` で `MilliOrbis-{EN}` を作成。

| Windowsの役割 | ファイル |
|---|---|
| 通常選択 | `arrow.cur` |
| ヘルプ選択 | `help.cur` |
| 動作中(バックグラウンド) | `appstar.cur` |
| ビジー | `wait.cur` |
| 精度選択 | `cross.cur` |
| テキスト選択 | `beam.cur` |
| 手書き | `pen.cur` |
| 使用不可 | `no.cur` |
| 垂直サイズ変更 | `sizens.cur` |
| 水平サイズ変更 | `sizewe.cur` |
| 斜めサイズ変更1 | `sizenwse.cur` |
| 斜めサイズ変更2 | `sizenesw.cur` |
| 移動 | `move.cur` |
| 予備選択 | `arrow.cur` |
| リンク選択 | `hand.cur` |
| 位置選択 | `hand.cur` |
| 人物選択 | `person.cur` |

## アンインストール

`設定 → Bluetoothとデバイス → マウス → その他のマウス設定 → ポインター` で配色を `Windows Default` に戻し、`C:\\Windows\\Cursors\\MilliOrbis-{EN}\\` を削除してください。

## ファイル

- `install.inf` — レジストリ登録用（`HKCU\\Control Panel\\Cursors\\Schemes`）。`Cursors.Files` と `[Strings]` のファイル名は完全一致している必要があります。
- `preview.png` — プレビュー画像（本カーソルの `arrow.png` を流用）

## ライセンス

- 個人で楽しむ範囲での利用のみ可。**再配布・転載・販売・商用利用はすべて禁止**です。
- 詳細は同梱の `LICENSE` を参照してください。
- キャラクター等の権利はミリプロ（Million Production）様に、カーソル画像の著作権は作者（すんすん）に帰属します。

## クレジット

- Cursor design: すんすん (@SunSunmachi)
- INF template: [david-ly gist](https://gist.github.com/david-ly/687922256a5c6a7b7b98a52980a984a1) (MIT), [Der-Floh/Cursor-Installer-Creator](https://github.com/Der-Floh/Cursor-Installer-Creator)
"""

README_MAC_TEMPLATE = """# MilliOrbis {JP} Cursors for Mac

![preview](preview.png)

**{JP}（{EN}）** のオリジナルカーソル 15種（`arrow` / `appstar` / `beam` / `cross` / `hand` / `help` / `move` / `no` / `pen` / `person` / `sizenesw` / `sizens` / `sizenwse` / `sizewe` / `wait`）を Mac で使えます。サイト内のカーソル切替は Mac のブラウザでも既に動作しますが、**システム全体**で使う場合は下記手順で適用してください。

## インストール（Mac）— Mousecape でワンクリック

1. [Mousecape](https://github.com/alexzielenski/Mousecape/releases) をダウンロード → `Mousecape.zip` を解凍 → `Mousecape.app` を `Applications` に移動 → 起動
2. 初回は `System Settings → Privacy & Security → Accessibility` で `Mousecape` を許可（ONにする）
3. 本 `MilliOrbis-{EN}-mac.zip` を解凍 → 中の `MilliOrbis-{EN}.cape` を **ダブルクリック** → Mousecapeに自動登録されます → リストから `MilliOrbis-{EN}` を選択 → `Apply`

> `MilliOrbis-{EN}.cape` は15種を一括登録するMousecape用ファイルです（Windowsの `install.inf` に相当）。ダブルクリックで完了し、手動のドラッグ＆ドロップは不要です。
> 旧来の手動登録も可能: `png/` 内の15枚を `File → New Cape` にドラッグ＆ドロップ（`hotspot.json` 参照）でも適用できます。

## サイト内での利用（Macでも即時）

Mac の Chrome / Safari でも `cursors.html` の `サイトで試す` ボタンやヘッダーの `カーソル` から即時切り替えできます（CSS `png` フォールバック）。

## ファイル

- `MilliOrbis-{EN}.cape` — **ワンクリック登録用**（Mousecapeでダブルクリック）
- `png/*.png` — 15種の透過PNG（32px、手動登録用フォールバック）
- `hotspot.json` — 各pngのホットスポット座標
- `preview.png` — プレビュー

## ライセンス

- 個人で楽しむ範囲での利用のみ可。**再配布・転載・販売・商用利用はすべて禁止**です。
- 詳細は同梱の `LICENSE` を参照してください。
- Cursor design: すんすん (@SunSunmachi)
"""

README_CHROMEBOOK_TEMPLATE = """# MilliOrbis {JP} Cursors for Chromebook

![preview](preview.png)

**{JP}（{EN}）** のオリジナルカーソル 15種を Chromebook の Chrome ブラウザで使えます。

> **Chromebook のシステム全体**ではカスタム画像のカーソルは OS制限で直接変更できません。**Chromeブラウザ内**でのみ有効です（Chromebookの主用途はブラウザのため実用上は十分です）。

## インストール（Chromebook）— 拡張で適用

1. Chromeウェブストアで [Custom Cursor for Chrome](https://chrome.google.com/webstore/detail/custom-cursor-for-chrome/ogdlpmhglpejoiomcodnpjnfgcpmgale) を `Add to Chrome` → `Add extension`
2. 拡張の管理画面（`chrome://extensions` → `Details` → `Extension options` または拡張アイコン → `Manage`）で `Upload cursor` から本 `MilliOrbis-{EN}-chromebook.zip` を解凍した `png/` 内の `png` を登録
   - 対応: `arrow=Normal`, `hand=Pointer`, `beam=Text`, `wait=Busy` 等（詳細は `hotspot.json` を参照）
3. 必要なら `Chromebook Settings → Accessibility → Cursor` でサイズ調整

## サイト内での利用

Chromebook でも `cursors.html` の `サイトで試す` やヘッダーの `カーソル` から即時切り替えできます。

## ファイル

- `png/*.png` — 15種の透過PNG（32px）
- `hotspot.json` — 各pngのホットスポット座標
- `preview.png` — プレビュー

## ライセンス

- 個人で楽しむ範囲での利用のみ可。**再配布・転載・販売・商用利用はすべて禁止**です。
- 詳細は同梱の `LICENSE` を参照してください。
- Cursor design: すんすん (@SunSunmachi)
"""

LICENSE_TEXT = """MilliOrbis オリジナルカーソル 利用許諾

Copyright (c) 2026 すんすん (@SunSunmachi) / Milli Orbis
キャラクター等の権利は Million Production（ミリプロ）様に帰属します。

1. 個人で楽しむ範囲（私的利用）に限り、無償で利用できます。
2. 再配布・転載・販売・貸与（有償・無償を問いません）、加工したものの配布、商用利用はすべて禁止します。
3. お友だちには配布ファイルではなく、配布ページを教えてあげてください。
4. 著作権表示の削除・改変は禁止します。

※ 本カーソルはファンによる二次創作です。ミリプロ公式様とは関係ありません。
"""

BAT_TEMPLATE = """@echo off
REM MilliOrbis {EN} Cursor — Install via INF (Admin required)
REM Right-click this file -> Run as administrator if double-click fails
echo Installing MilliOrbis-{EN} cursor scheme...
rundll32.exe setupapi,InstallHinfSection DefaultInstall 132 "%~dp0install.inf"
if %errorlevel% neq 0 (
  echo Failed. Try right-click install.inf -> Install as Administrator.
  pause
  exit /b 1
)
echo Done. Open Settings -> Bluetooth ^& devices -> Mouse -> Additional mouse settings -> Pointers and select "MilliOrbis-{EN}".
pause
"""

def _extract_hotspots(cur_path):
    """Read xHot,yHot from .cur file header (first entry)"""
    try:
        data = cur_path.read_bytes()
        import struct
        reserved, typ, count = struct.unpack_from("<HHH", data, 0)
        if count < 1:
            return [0,0]
        bW,bH,bC,bR,wPlanes,wBitCount,dwBytes,dwOff = struct.unpack_from("<BBBBHHII", data, 6)
        # ICONDIRENTRY is 16 bytes, image data starts at dwOff
        # BITMAPINFOHEADER is 40 bytes, hotspot is not in BMP but in cur entry? For .cur, hotspot is wPlanes/xHot and wBitCount/yHot? Actually CUR uses wPlanes as xHot, wBitCount as yHot
        xHot = wPlanes
        yHot = wBitCount
        return [xHot, yHot]
    except Exception:
        return [0,0]

# Mac .cape generation: Windows 15 -> Apple identifiers
CAPE_MAP = {
    "arrow": "com.apple.coregraphics.Arrow",
    "beam": "com.apple.coregraphics.IBeam",
    "cross": "com.apple.coregraphics.Crosshair",
    "hand": "com.apple.coregraphics.PointingHand",
    "wait": "com.apple.coregraphics.Wait",
    "appstar": "com.apple.coregraphics.Wait",
    "help": "com.apple.coregraphics.Help",
    "move": "com.apple.coregraphics.Move",
    "no": "com.apple.coregraphics.NotAllowed",
    "pen": "com.apple.coregraphics.IBeam",
    "person": "com.apple.coregraphics.PointingHand",
    # resize variants map to Apple resize cursors / numeric fallbacks
    "sizenesw": "com.apple.cursor.3",
    "sizens": "com.apple.coregraphics.ResizeUpDown",
    "sizenwse": "com.apple.cursor.5",
    "sizewe": "com.apple.coregraphics.ResizeLeftRight",
}

def _build_cape(en, jp, png_dir, hotspot, out_path):
    """Build minimal Mousecape .cape plist with 15 cursors"""
    try:
        from PIL import Image
    except Exception as e:
        print(f" cape skip {en}: Pillow missing {e}")
        return False
    cursors = {}
    for png_name, hs in hotspot.items():
        base = png_name.replace(".png", "")
        apple_id = CAPE_MAP.get(base)
        if not apple_id:
            continue
        png_path = png_dir / png_name
        if not png_path.exists():
            continue
        # skip duplicate Apple ids (keep first)
        if apple_id in cursors:
            continue
        try:
            im = Image.open(png_path)
            w, h = im.size
        except Exception:
            w, h = 32, 32
        # load png bytes as Data
        data = png_path.read_bytes()
        # PointsWide/High = image size at 1x
        # HotSpot from hotspot.json
        hx, hy = hs if isinstance(hs, (list, tuple)) and len(hs)==2 else (0,0)
        cursors[apple_id] = {
            "FrameCount": 1,
            "FrameDuration": 1.0,
            "HotSpotX": float(hx),
            "HotSpotY": float(hy),
            "PointsWide": float(w),
            "PointsHigh": float(h),
            "Representations": [data],
        }
    # fallback: ensure at least Arrow exists, else add arrow.png
    if "com.apple.coregraphics.Arrow" not in cursors:
        ap = png_dir / "arrow.png"
        if ap.exists():
            hs = hotspot.get("arrow.png", [4,4])
            data = ap.read_bytes()
            cursors["com.apple.coregraphics.Arrow"] = {
                "FrameCount": 1, "FrameDuration": 1.0,
                "HotSpotX": float(hs[0]), "HotSpotY": float(hs[1]),
                "PointsWide": 32.0, "PointsHigh": 32.0,
                "Representations": [data],
            }
    cape = {
        "Author": "Milli Orbis",
        "CapeName": f"MilliOrbis-{en}",
        "CapeVersion": 1.0,
        "Identifier": f"com.milli-orbis.{en.lower()}",
        "Version": 2.0,
        "MinimumVersion": 2.0,
        "Cloud": False,
        "HiDPI": True,
        "Cursors": cursors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "wb") as f:
        plistlib.dump(cape, f, fmt=plistlib.FMT_XML)
    return True

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--win", action="store_true", help="Generate Windows zips")
    parser.add_argument("--mac", action="store_true", help="Generate Mac zips")
    parser.add_argument("--chromebook", action="store_true", help="Generate Chromebook zips")
    parser.add_argument("--all", action="store_true", help="Generate all")
    args = parser.parse_args()
    do_win = args.win or args.all or (not args.win and not args.mac and not args.chromebook)
    do_mac = args.mac or args.all
    do_cb = args.chromebook or args.all

    CURSORS_ROOT.mkdir(parents=True, exist_ok=True)
    DIST_ROOT.mkdir(parents=True, exist_ok=True)
    # Clean dist subfolders based on flags
    if args.all and DIST_ROOT.exists():
        shutil.rmtree(DIST_ROOT)
        DIST_ROOT.mkdir(parents=True, exist_ok=True)
    (DIST_ROOT / "win").mkdir(parents=True, exist_ok=True)
    (DIST_ROOT / "mac").mkdir(parents=True, exist_ok=True)
    (DIST_ROOT / "chromebook").mkdir(parents=True, exist_ok=True)
    # Keep legacy flat for backward compat (win)
    # Clean legacy flat zips if regenerating win
    if do_win:
        for p in DIST_ROOT.glob("*.zip"):
            p.unlink()

    for tid, en, jp in TALENTS:
        cur_folder_name = CUR_FOLDER[tid]
        scheme = f"MilliOrbis-{en}"
        cur_dir = CURSORS_ROOT / cur_folder_name
        if not cur_dir.exists():
            print(f"skip {tid}: no folder {cur_dir}")
            continue
        # Verify 15 files exist
        missing = [f for f in FIFTEEN if not (cur_dir / f).exists()]
        if missing:
            print(f"warn {tid} missing {missing}")

        # Generate install.inf, README.md, LICENSE, install.bat, preview.png inside cur_dir (for verification)
        inf_content = INF_TEMPLATE.format(SCHEME=scheme, JP=jp, EN=en)
        readme_content = README_TEMPLATE.format(JP=jp, EN=en)
        bat_content = BAT_TEMPLATE.format(EN=en)

        # Write to cursor folder (for direct browsing) and also to dist staging
        (cur_dir / "install.inf").write_text(inf_content, encoding="utf-8")
        (cur_dir / "README.md").write_text(readme_content, encoding="utf-8")
        (cur_dir / "LICENSE").write_text(LICENSE_TEXT, encoding="utf-8")
        (cur_dir / "install.bat").write_text(bat_content, encoding="utf-8")
        # preview.png: copy from root png (arrow-derived)
        src_png = CURSORS_ROOT / f"{cur_folder_name}.png"
        dst_preview = cur_dir / "preview.png"
        if src_png.exists():
            shutil.copy(src_png, dst_preview)
        else:
            # fallback
            print(f"no preview source for {tid}")

        # Now create zips per OS
        # -- Win
        if do_win:
            zip_name = f"MilliOrbis-{en}.zip"
            for out_dir in [DIST_ROOT, DIST_ROOT / "win"]:
                out_dir.mkdir(parents=True, exist_ok=True)
                zip_path = out_dir / zip_name
                with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                    base = f"MilliOrbis-{en}/"
                    for fname in FIFTEEN:
                        src = cur_dir / fname
                        if src.exists():
                            zf.write(src, base + fname)
                    zf.write(cur_dir / "install.inf", base + "install.inf")
                    zf.write(cur_dir / "README.md", base + "README.md")
                    zf.write(cur_dir / "LICENSE", base + "LICENSE")
                    zf.write(cur_dir / "install.bat", base + "install.bat")
                    if dst_preview.exists():
                        zf.write(dst_preview, base + "preview.png")
                print(f"generated win {zip_path} ({zip_path.stat().st_size} bytes)")
        # -- Mac / Chromebook: png + hotspot.json
        # Generate png dir + hotspot.json once per talent
        # Ensure png extraction (Pillow) – use existing root png as preview but also extract 15 pngs
        if do_mac or do_cb:
            from PIL import Image
            png_dir = cur_dir / "png"
            png_dir.mkdir(exist_ok=True)
            hotspot = {}
            for fname in FIFTEEN:
                cur_path = cur_dir / fname
                png_name = fname.replace(".cur", ".png")
                dst_png = png_dir / png_name
                try:
                    im = Image.open(cur_path)
                    im.save(dst_png, "PNG")
                    hotspot[png_name] = _extract_hotspots(cur_path)
                except Exception as e:
                    # fallback copy existing root png for arrow
                    if png_name == "arrow.png" and (CURSORS_ROOT / f"{cur_folder_name}.png").exists():
                        shutil.copy(CURSORS_ROOT / f"{cur_folder_name}.png", dst_png)
                        hotspot[png_name] = [1,1]
                    else:
                        print(f" png extract failed {tid}/{fname}: {e}")
            # also copy preview
            if src_png.exists():
                shutil.copy(src_png, png_dir / "preview.png")
            (cur_dir / "hotspot.json").write_text(json.dumps(hotspot, indent=2, ensure_ascii=False), encoding="utf-8")
            shutil.copy(cur_dir / "hotspot.json", png_dir / "hotspot.json")
            # Generate .cape for Mac (wraps png + hotspot) — Windows-like one-click
            cape_path = None
            if do_mac:
                cape_path = cur_dir / f"MilliOrbis-{en}.cape"
                ok = _build_cape(en, jp, png_dir, hotspot, cape_path)
                if ok:
                    print(f"generated cape {cape_path} ({cape_path.stat().st_size} bytes)")
                    # also copy standalone .cape to dist/mac for direct download
                    try:
                        shutil.copy(cape_path, DIST_ROOT / "mac" / cape_path.name)
                    except Exception:
                        pass
                else:
                    cape_path = None
            # Generate mac/chromebook zips
            for kind, readme_tmpl in [("mac", README_MAC_TEMPLATE), ("chromebook", README_CHROMEBOOK_TEMPLATE)]:
                if (kind == "mac" and not do_mac) or (kind == "chromebook" and not do_cb):
                    continue
                readme_mac = readme_tmpl.format(JP=jp, EN=en)
                # write README for this kind (overwrite generic for now, but keep win README separately? Use per-kind readme in zip)
                out_sub = DIST_ROOT / kind
                out_sub.mkdir(parents=True, exist_ok=True)
                zip_path = out_sub / f"MilliOrbis-{en}-{kind}.zip"
                with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                    base = f"MilliOrbis-{en}-{kind}/"
                    # include .cape for mac (one-click)
                    if kind == "mac" and cape_path and cape_path.exists():
                        zf.write(cape_path, base + cape_path.name)
                    # include pngs (fallback manual)
                    for p in png_dir.glob("*.png"):
                        zf.write(p, base + "png/" + p.name)
                    zf.write(cur_dir / "hotspot.json", base + "hotspot.json")
                    # Also include preview at top
                    if dst_preview.exists():
                        zf.write(dst_preview, base + "preview.png")
                    zf.writestr(base + "README.md", readme_mac)
                    zf.writestr(base + "LICENSE", LICENSE_TEXT)
                print(f"generated {kind} {zip_path} ({zip_path.stat().st_size} bytes)")

    # Create bundle zips
    if do_win:
        bundle_path = DIST_ROOT / "MilliOrbis-Cursors-All.zip"
        # also win subfolder
        for bpath in [DIST_ROOT / "MilliOrbis-Cursors-All.zip", DIST_ROOT / "win" / "MilliOrbis-Cursors-All.zip"]:
            bpath.parent.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(bpath, "w", zipfile.ZIP_DEFLATED) as zf:
                for tid, en, jp in TALENTS:
                    cur_dir = CURSORS_ROOT / CUR_FOLDER[tid]
                    base = f"MilliOrbis-{en}/"
                    for fname in FIFTEEN:
                        src = cur_dir / fname
                        if src.exists():
                            zf.write(src, base + fname)
                    zf.write(cur_dir / "install.inf", base + "install.inf")
                    zf.write(cur_dir / "README.md", base + "README.md")
                bundle_readme = "# MilliOrbis Cursors — All Talents Bundle\n\n各タレントフォルダに `install.inf` が入っています。各フォルダで右クリック → インストール してください。\n\n- Scheme名: `MilliOrbis-{Konomi|Nono|...}`\n- 1タレントあたり15種\n- Windows 10/11 対応\n\n## ライセンス\n\n- 個人で楽しむ範囲での利用のみ可。再配布・転載・販売・商用利用はすべて禁止です。詳細は `LICENSE` を参照してください。\n"
                zf.writestr("README.md", bundle_readme)
                zf.writestr("LICENSE", LICENSE_TEXT)
            print(f"generated bundle {bpath} ({bpath.stat().st_size} bytes)")
    if do_mac:
        for kind in ["mac", "chromebook"]:
            if (kind == "mac" and not do_mac) or (kind == "chromebook" and not do_cb):
                continue
            bundle_path = DIST_ROOT / kind / f"MilliOrbis-Cursors-All-{kind}.zip"
            bundle_path.parent.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(bundle_path, "w", zipfile.ZIP_DEFLATED) as zf:
                for tid, en, jp in TALENTS:
                    cur_dir = CURSORS_ROOT / CUR_FOLDER[tid]
                    base = f"MilliOrbis-{en}-{kind}/"
                    png_dir = cur_dir / "png"
                    # include .cape for mac bundle
                    if kind == "mac":
                        cp = cur_dir / f"MilliOrbis-{en}.cape"
                        if cp.exists():
                            zf.write(cp, base + cp.name)
                    for p in png_dir.glob("*.png"):
                        zf.write(p, base + "png/" + p.name)
                    if (cur_dir / "hotspot.json").exists():
                        zf.write(cur_dir / "hotspot.json", base + "hotspot.json")
                if kind == "mac":
                    zf.writestr("README.md", f"# MilliOrbis Cursors — All Mac Bundle\n\n各タレントの .cape (ワンクリック) + png セットです。`*.cape` をダブルクリックで Mousecape に一括登録できます。\n\n## ライセンス\n\n- 個人で楽しむ範囲での利用のみ可。再配布・転載・販売・商用利用はすべて禁止です。詳細は `LICENSE` を参照してください。\n")
                else:
                    zf.writestr("README.md", f"# MilliOrbis Cursors — All {kind} Bundle\n\n各タレントの png セットです。\n\n## ライセンス\n\n- 個人で楽しむ範囲での利用のみ可。再配布・転載・販売・商用利用はすべて禁止です。詳細は `LICENSE` を参照してください。\n")
                zf.writestr("LICENSE", LICENSE_TEXT)
            print(f"generated bundle {bundle_path} ({bundle_path.stat().st_size} bytes)")
    # List
    for p in sorted(DIST_ROOT.rglob("*.zip")):
        print(f" - {p.relative_to(DIST_ROOT)}: {p.stat().st_size} bytes")

if __name__ == "__main__":
    main()
